### ISSUE TITLE
Bug in DepoFluxWriter when "incorrecting" the timing?

### ISSUE THREAD

**Issue by SFBayLaser** [LArSoft/larwirecell#39]
Unfortunately, the setup of ICARUS (and all other operating LArTPCs I am aware of) require "incorrecting" the time offsets to get SimChannel agreement with the output of the detector simulation and deconvolution.  Following the directions in the nice documentation located [here](https://github.com/LArSoft/larwirecell/blob/master/larwirecell/docs/depofluxwriter.org), resulted in nonsensical tdc times which don't appear to either be on the waveforms or anywhere close to pulses on those waveforms. In looking at the code I am fairly certain that the issue is at line 274 ([here](https://github.com/LArSoft/larwirecell/blob/90150609fde0e851a4e5ee44ec211123b55a6e55/larwirecell/Components/DepoFluxWriter.cxx#L274)) in [DepoFluxWriter](https://github.com/LArSoft/larwirecell/blob/master/larwirecell/Components/DepoFluxWriter.cxx). 

If I modify this line to:

> const unsigned int tdc = m_tbins.center(tbin)/m_tbins.binsize() + toffset_bin + m_tick_offsets[iplane];

Then I am able to get tdc values that are "in range" and agree with pulses seen on waveforms (with a caveat about differences in drift velocities leading to slight offsets between RawDigit peaks and SimChannel deposits). 

How can we address this relatively quickly? The ICARUS ML effort really needs to be able to confirm that the output will allow them to continue with training of various networks in their code. 

Thanks!

**Comment by lgarren** [comment]
@SFBayLaser Please make a PR

**Comment by lgarren** [comment]
FYI - providing a PR is the fastest way to get this fixed.

**Comment by lgarren** [comment]
Closed per conversation on https://github.com/LArSoft/larwirecell/pull/40
